config/routes.rb
Treebook::Application.routes.draw do
  get "profiles/show"

  devise_for :users

  devise_scope :user do
  get 'log_in', to: "devise/sessions#new"
  get 'register', to: "devise/registrations#new"
  end
  get 'feed', to: "statuses#index", as: :feed
  resources :statuses
  root to: "statuses#index"

  get "/:id", to: 'profiles#show'
  

end

app/models/status.rb
class Status < ActiveRecord::Base
  attr_accessible :content, :user_id
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :first_name, :last_name, :profile_name, :email, :password, :password_confirmation, :remember_me
  has_many :statuses
  def full_name
  	first_name + " " + last_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
  	@user = User.find_by_profile_name(params[:id])
  	if @user
  		@statuses = @user.statuses.all
  		render action: :show
  	else
  	render file: 'public/404', status: 404, formats: [:html]
  	end
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @statuses }
    end
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
    @status = Status.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/new
  # GET /statuses/new.json
  def new
    @status = Status.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/1/edit
  def edit
    @status = Status.find(params[:id])
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(params[:status])

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render json: @status, status: :created, location: @status }
      else
        format.html { render action: "new" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /statuses/1
  # PUT /statuses/1.json
  def update
    @status = Status.find(params[:id])

    respond_to do |format|
      if @status.update_attributes(params[:status])
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status = Status.find(params[:id])
    @status.destroy

    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def flash_class(type)
		case (type)
		when :alert
			"alert-danger"
		when :notice
			"alert-success"
		end

	end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Treebook</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	
			<div class="navbar navbar-inverse navbar-fixed-top ">
			<div class="container">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".nav-collapse">
		          <span class="icon-bar"></span>
		          <span class="icon-bar"></span>
		          <span class="icon-bar"></span>
		        </button>
	  			<a href="#" class="navbar-brand">Treebook</a>
	  			<div class="nav-collapse collapse">
          			<ul class="nav navbar-nav">
			            <li><%= link_to "Estados", feed_path %></li>
		          </ul>
		          <ul class="nav navbar-nav pull-right">
		          	<% if user_signed_in? %>
		          	<li><%= link_to current_user.full_name, edit_user_registration_path  %></li>
		          	<li><%= link_to "logout", destroy_user_session_path, :method => :delete  %></a></li><% else %>
		          	<li><%= link_to "Register", register_path %></a></li>
			            <li><%= link_to "login", log_in_path %></a></li>
			            <% end %>
		          </ul>
       			</div><!-- nav-collapse -->
	  		</div><!-- navbar container -->
		</div><!-- navbar -->
		<div class="container">

			<% flash.each do |type,message| %>
				<div class="alert <%= flash_class type %>">
 					<button type="button" class="close" data-dismiss="alert">&times;</button>
 					<%= message %>
 				</div>
			<% end %>



<%= yield %>

	</div><!-- container -->
</body>
</html>

app/views/profiles/show.html.erb
<div class="page-header">
	<h1><%= @user.full_name %></h1>
</div>

<% if @statuses %>
	<% @statuses.each do |status| %>
		<div class="well">
			<%= status.content %>
			<hr/>
			<%= link_to time_ago_in_words(status.created_at), status_path(status) %>
		</div>
	<% end %>
<% end %>

app/views/statuses/_form.html.erb
<%= simple_form_for(@status, html: {class: "form-horizontal"}) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.input :user_id, collection: User.all, label_method: :full_name , input_html: {class: "form-control"},label_html: {class: "control-label"} %>

  <%= f.input :content, input_html: {class: "form-control"},label_html: {class: "control-label"} %>

  <div class="actions">
    <%= f.button :submit, class: "btn-default" %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editar Estado</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<div class="page-header">
<h1>Todos los Estados <small>Subtexto</small></h1>
</div><!-- page-header -->
<%= link_to "Nuevo Estado", new_status_path, class: "btn btn-default btn-success" %>

<% @statuses.each do |status| %>
<div class="status">
  <strong> <%= status.user.full_name %></strong>
  <p><%= status.content %></p>
  <div class="meta">
    <%= link_to time_ago_in_words(status.created_at) + " ago", status %> 
    <span class="admin">
      | <%= link_to "Editar", edit_status_path(status) %> |
      <%= link_to "Borrar", status, method: :delete, data: { confirm: "Esta seguro que desea borrar el estado?"} %>
    </span><!-- admin -->
  </div><!-- admin -->
</div><!-- status -->

<% end %>

app/views/statuses/new.html.erb
<fieldset>
	<legend><h2>Nuevo Estado</h2></legend>
<%= render 'form' %>

<%= link_to 'Back', statuses_path %>
</fieldset><!-- fieldset -->

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @status.user.full_name %>
 
</p>

<p>
  <b>Content:</b>
  <%= @status.content %>
</p>


<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>